-
  branches:
    only:
      - master

  configuration: Release

  platform:
      - x86
      - x64
      - Any CPU

  image: Visual Studio 2017

  pull_requests:
    do_not_increment_build_number: false

  init:
    - ps: "if (($env:APPVEYOR_REPO_COMMIT_MESSAGE -match '\\d+\\.\\d+\\.\\d+$') -And ($env:APPVEYOR_REPO_BRANCH -eq 'master'))\n{\n  Set-AppveyorBuildVariable VERSION $env:APPVEYOR_REPO_COMMIT_MESSAGE\n} \nelse \n{\n  Set-AppveyorBuildVariable VERSION 0.0.0\n}"
   
  before_build: nuget restore source/Depressurizer.sln

  assembly_info:
    patch: true
    file: source\Depressurizer\Properties\AssemblyInfo.cs
    assembly_version: $(VERSION)
    assembly_file_version: $(VERSION).$(APPVEYOR_BUILD_NUMBER)
    assembly_informational_version: $(VERSION)

  artifacts:
    - path: source\Depressurizer\bin\Release
      name: Depressurizer
      type: zip

    - path: source\Depressurizer\bin\$(platform)\Release
      name: Depressurizer-$(platform)
      type: zip

  deploy:
    - provider: GitHub
      tag: v$(APPVEYOR_REPO_COMMIT_MESSAGE)
      release: Depressurizer v$(APPVEYOR_REPO_COMMIT_MESSAGE)
      auth_token:
        secure: OmzEeKzHCDVoUzePOb3TSFMap7zIxcr4RcqF4ynEArYV8DXShUjfNh01csgtJQzE
      draft: true
      artifact: /.*\.zip/
      force_update: true
      on:
        APPVEYOR_REPO_COMMIT_MESSAGE: /\d+\.\d+\.\d+$/
        APPVEYOR_REPO_BRANCH: 'master'

-
  branches:
    except:
      - master

  configuration: Debug

  platform:
    - x86
    - x64
    - Any CPU

  skip_commits:
    files:
      - .github/*

  image: Visual Studio 2017

  pull_requests:
    do_not_increment_build_number: false

  before_build: nuget restore source/Depressurizer.sln

  build:
    project: source/Depressurizer.sln
    verbosity: quiet
